services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: my-go-server

    ports:
      - "${HTTP_PORT}:8080"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

    networks:
      - app-network

  postgres:
    image: ${POSTGRES_IMAGE_NAME}

    container_name: postgres-reviewer

    env_file:
      - .env

    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      # Настраиваем проверку готовности контейнера — pg_isready проверяет, принимает ли база подключения
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    # Автоматически перезапускаем контейнер, если он аварийно завершился.
    # Если контейнер был остановлен вручную — не перезапускаем
    restart: unless-stopped

    networks:
      - app-network

# Docker network для возможного расширения проекта
networks:
  app-network:
    driver: bridge

volumes:
  pgdata: